---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hes-corp-notice-api-conf
  namespace: fa22-5740054-crm
data:
  hes-corp-notice-api.yml: |

    # OWK 的配置
    owk:
      client:
        gateway: http://test-nbowk-plus.bcs.cmbchina.cn # owk 网关
        appId: oa-cwbx  # 在2.0 中注册 appId 和  appPwd
        appPwd: 6Nd4XHAtoabCN8xS9hcNhBPc1buYrEi+6QBRFEZvmZ0=
      store: # 引入 owk-store 后支持ESC.
        policy: ecs
        ecs:
          end-point: http://99.12.100.29:9020
          access-key: lq01_user4
          secret-key: 5zPZmWretfc+yOcQ+sMqZeMVZAf6CqneMVJaFbbn
          bucket-name: lq01_06_ocmhk201901.11
          url-expire-seconds: 300
          gateway:
            host: http://99.12.227.173
            app-id: lq01_user4
            app-key: 26caff63-6a11-4ecd-bebe-f60a43598d59
      osf-client: # osf支持
        server: http://99.6.136.73:8888/osf-service
        app-id: OWK
        app-pwd: OWK

    spring:
      datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:D:/zry/software/sqliteDb/hes.db
        username:
        password:

      servlet: # servlet 的文件文件上传大小限制。
        multipart:
          enabled: true
          max-file-size: 20MB
          max-request-size: 50MB



    # mybatis 的基本设置，不要指定 location.
    mybatis:
      configuration:
        log-impl:  org.apache.ibatis.logging.slf4j.Slf4jImpl
        log-prefix: org.apache.ibatis.
        map-underscore-to-camel-case: true # 支持驼峰转下划线
      mapper-locations: classpath:mybatis/mapper/*.xml
    pagehelper: # pageHelper 分页插件设置
      auto-runtime-dialect: true # 自动切换方言,不开启此项的话，会导致不同数据库sql 格式错误

    # 日志
    logging:
      level:
        root: INFO
        com.cmbnt.owk: DEBUG
        com.cmbchina.owk: DEBUG
        org.springframework: DEBUG
        org.apache.ibatis: DEBUG
        com.cmbnb: DEBUG # 添加宁波分行的log.

    server:
      port: 8080
    jasypt:
      encryptor:
    #    password: ${ENCRYPTOR_PASSWORD}
        password: gxxd

    ksxt:
      msg: # 发送信息接口配置.
        zhRobotSendUrl: http://msg-notice-sys-mysql.bcs.cmbchina.cn/msg-notice-sys/msgNotice/zhrobotMsg.do # 招呼robot 发送接口.
        mngUsr: 295461 # 接口发送人.

    config:
      checkDzhdCron: 0/2 * * * * ?  # 定时任务cron


    wechat:
      corpid: ww4d810f1479a29e4b
      agentId: 1000012
      corpsecret: IZw9gfoN_l3ORgZBb1vRGipv2nGkq_GOlh8rRv0dj_o
      accessTokenUrl: https://qyapi.weixin.qq.com/cgi-bin/gettoken
      msgSendUrl: https://qyapi.weixin.qq.com/cgi-bin/message/send
      msgSendToGroupUrl: https://qyapi.weixin.qq.com/cgi-bin/appchat/send   # 群聊发送消息 接口
      mediaUploadUrl: https://qyapi.weixin.qq.com/cgi-bin/media/upload
      skGroupChatId: wrW9_0EAAAb1Mz1w0YL10rl5mhWr8_Bg   # 收款- 发送文件到 群聊，这个群聊的 chatid

    cbs:
      requestHttpUrl: http://127.0.0.1:10666
      bwKey: 2
      CRC32_PASSWORD: CMBChina2009
      CRC32_PREFIX: Z
      actNbr: 591915131410208,310899991010008776083,755915678910506,755915678910202  # 交易账户



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hes-corp-notice-api
  labels:
    app: hes-corp-notice-api
  namespace: fa22-5740054-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hes-corp-notice-api
  template:
    metadata:
      labels:
        app: hes-corp-notice-api
    spec:
      restartPolicy: Always
      containers:
        - name: hes-corp-notice-api
          image: [image]
          imagePullPolicy: Always
          volumeMounts:
            - name: hes-corp-notice-api-volumn
              subPath: hes-corp-notice-api.yml
              mountPath: /opt/hes-corp-notice-api.yml
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: '1'
              memory: 2G
            limits:
              cpu: '1'
              memory: 2G
          env:
            - name: JAVA_OPTS
              value: '-Xms1363148K -XX:MetaspaceSize=209715K -Xss699K -Xmx1363148K -XX:MaxMetaspaceSize=209715K -Dspring.config.location=/opt/hes-corp-notice-api.yml'
            - name: LANG
              value: en_US.utf8
            - name: TZ
              value: Asia/Shanghai
      volumes:
        - name: hes-corp-notice-api-volumn
          configMap:
            name: hes-corp-notice-api-conf
---
kind: Service
apiVersion: v1
metadata:
  name: hes-corp-notice-api
  labels:
    app: hes-corp-notice-api
  namespace: fa22-5740054-crm
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      protocol: TCP
      name: 8080-8080
      port: 8080
  selector:
    app: hes-corp-notice-api
