---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mortgage-info-api-conf
  namespace: fa31-5740039-lsxd
data:
  mortgage-info-api.yml: |

    # OWK 的配置
    owk:
      client:
        gateway: http://test-nbowk-plus.bcs.cmbchina.cn # owk 网关
        appId: oa-cwbx  # 在2.0 中注册 appId 和  appPwd
        appPwd: 6Nd4XHAtoabCN8xS9hcNhBPc1buYrEi+6QBRFEZvmZ0=
      store: # 引入 owk-store 后支持ESC.
        policy: ecs
        ecs:
          end-point: http://99.12.100.29:9020
          access-key: lq01_user4
          secret-key: 5zPZmWretfc+yOcQ+sMqZeMVZAf6CqneMVJaFbbn
          bucket-name: lq01_06_ocmhk201901.11
          url-expire-seconds: 300
          gateway:
            host: http://99.12.227.173
            app-id: lq01_user4
            app-key: 26caff63-6a11-4ecd-bebe-f60a43598d59
      osf-client: # osf支持
        server: http://99.6.136.73:8888/osf-service
        app-id: OWK
        app-pwd: OWK

    spring:
      datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://55.14.89.243:3306/nbxcx?characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: nbxcx
        password: ENC(kOyW78KVj6JQauJa+sYUW0AJEf0xf9ew)

      servlet: # servlet 的文件文件上传大小限制。
        multipart:
          enabled: true
          max-file-size: 20MB
          max-request-size: 50MB



    # mybatis 的基本设置，不要指定 location.
    mybatis:
      configuration:
        log-impl:  org.apache.ibatis.logging.slf4j.Slf4jImpl
        log-prefix: org.apache.ibatis.
        map-underscore-to-camel-case: true # 支持驼峰转下划线
      mapper-locations: classpath:mybatis/mapper/*.xml
    pagehelper: # pageHelper 分页插件设置
      auto-runtime-dialect: true # 自动切换方言,不开启此项的话，会导致不同数据库sql 格式错误

    # 日志
    logging:
      level:
        root: INFO
        com.cmbnt.owk: DEBUG
        com.cmbchina.owk: DEBUG
        org.springframework: DEBUG
        org.apache.ibatis: DEBUG
        com.cmbnb: DEBUG # 添加宁波分行的log.

    server:
      port: 8080
    jasypt:
      encryptor:
    #    password: ${ENCRYPTOR_PASSWORD}
        password: gxxd

    ksxt:
      msg: # 发送信息接口配置.
        zhRobotSendUrl: http://msg-notice-sys-mysql.bcs.cmbchina.cn/msg-notice-sys/msgNotice/zhrobotMsg.do # 招呼robot 发送接口.
        mngUsr: 295461 # 接口发送人.


    webservice:
      server: http://99.62.247.75:8803
      visitIp: 60.24.1.28
      organCode: C1030833000191

      url:
        dgcx: ${webservice.server}/services/dgcx?wsdl
        mycx: ${webservice.server}/services/mycx?wsdl
        plcx: ${webservice.server}/services/plcx?wsdl
        plxz: ${webservice.server}/services/plxz?wsdl
        rqqjcx: ${webservice.server}/services/rqqjcx?wsdl
      sm2:
        private-key: 32eee565c9e1a963b693e4edf77d0913d635dd04bebbd70a6d55765d61bd4a1f
      sm4:
        privateKey: 40E8C55D85E74DCC80E382CE416001A4


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mortgage-info-api
  labels:
    app: mortgage-info-api
  namespace: fa31-5740039-lsxd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mortgage-info-api
  template:
    metadata:
      labels:
        app: mortgage-info-api
    spec:
      restartPolicy: Always
      containers:
        - name: mortgage-info-api
          image: [image]
          imagePullPolicy: Always
          volumeMounts:
            - name: mortgage-info-api-volumn
              subPath: mortgage-info-api.yml
              mountPath: /opt/mortgage-info-api.yml
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: '1'
              memory: 2G
            limits:
              cpu: '1'
              memory: 2G
          env:
            - name: JAVA_OPTS
              value: '-Xms1363148K -XX:MetaspaceSize=209715K -Xss699K -Xmx1363148K -XX:MaxMetaspaceSize=209715K -Dspring.config.location=/opt/mortgage-info-api.yml'
            - name: LANG
              value: en_US.utf8
            - name: TZ
              value: Asia/Shanghai
      volumes:
        - name: mortgage-info-api-volumn
          configMap:
            name: mortgage-info-api-conf
---
kind: Service
apiVersion: v1
metadata:
  name: mortgage-info-api
  labels:
    app: mortgage-info-api
  namespace: fa31-5740039-lsxd
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      protocol: TCP
      name: 8080-8080
      port: 8080
  selector:
    app: mortgage-info-api
